### ISSUE TITLE
安装时产生以下错误日志 无法安装成功

### ISSUE THREAD

**Issue by ICyChain** [sl1673495/vue-netease-music#40]
安装时产生以下错误日志
`0 verbose cli [
0 verbose cli   '/usr/local/node/bin/node',
0 verbose cli   '/usr/local/node/bin/npm',
0 verbose cli   'run',
0 verbose cli   'devnpm',
0 verbose cli   'run',
0 verbose cli   'dev'
0 verbose cli ]
1 info using npm@7.5.1
2 info using node@v15.8.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/node/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/www/wwwroot/NeteaseCloudMusic/vue-netease-music/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/node/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session af6ef889a20ea736
20 timing npm:load Completed in 17ms
21 timing command:run-script Completed in 2ms
22 verbose stack Error: missing script: devnpm
22 verbose stack     at runScript (/usr/local/node/lib/node_modules/npm/lib/run-script.js:54:11)
23 verbose cwd /www/wwwroot/NeteaseCloudMusic/vue-netease-music
24 verbose Linux 3.10.0-957.27.2.el7.x86_64
25 verbose argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "run" "devnpm" "run" "dev"
26 verbose node v15.8.0
27 verbose npm  v7.5.1
"~/.npm/_logs/2021-02-07T09_29_56_961Z-debug.log" 38L, 1687C
`

**Comment by ICyChain** [comment]
```
0 verbose cli [
0 verbose cli   '/usr/local/node/bin/node',
0 verbose cli   '/usr/local/node/bin/npm',
0 verbose cli   'run',
0 verbose cli   'devnpm',
0 verbose cli   'run',
0 verbose cli   'dev'
0 verbose cli ]
1 info using npm@7.5.1
2 info using node@v15.8.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:/usr/local/node/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/www/wwwroot/NeteaseCloudMusic/vue-netease-music/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/node/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 8ms
19 verbose npm-session af6ef889a20ea736
20 timing npm:load Completed in 17ms
21 timing command:run-script Completed in 2ms
22 verbose stack Error: missing script: devnpm
22 verbose stack     at runScript (/usr/local/node/lib/node_modules/npm/lib/run-script.js:54:11)
23 verbose cwd /www/wwwroot/NeteaseCloudMusic/vue-netease-music
24 verbose Linux 3.10.0-957.27.2.el7.x86_64
25 verbose argv "/usr/local/node/bin/node" "/usr/local/node/bin/npm" "run" "devnpm" "run" "dev"
26 verbose node v15.8.0
27 verbose npm  v7.5.1
"~/.npm/_logs/2021-02-07T09_29_56_961Z-debug.log" 38L, 1687C

```
